# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=3)),
                ('klass', models.IntegerField(choices=[(1, b'Freshman'), (2, b'Sophomore'), (3, b'Junior'), (4, b'Senior')])),
                ('squad', models.IntegerField(choices=[(1, b'Freshman'), (2, b'JV'), (3, b'Varsity')])),
                ('position', models.IntegerField(choices=[(1, b'Forward'), (2, b'Midfielder'), (3, b'Defender'), (4, b'Goalkeeper')])),
            ],
        ),
    ]
