# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('ordering', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'coaches',
            },
        ),
    ]
