# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171021_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.IntegerField(choices=[(1, 'Freshman'), (2, 'JV'), (3, 'Varsity')])),
                ('scrimmage', models.BooleanField()),
                ('tournament', models.BooleanField()),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('opponent', models.CharField(max_length=64)),
                ('location', models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'Away')], null=True)),
                ('location_name', models.CharField(blank=True, max_length=64)),
                ('location_map_url', models.URLField(blank=True)),
                ('whs_score', models.IntegerField(blank=True, null=True)),
                ('opponent_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
