# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171029_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='location',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
    ]
