# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171029_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='klass',
            field=models.IntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(1, 'Forward'), (2, 'Midfielder'), (3, 'Defender'), (4, 'Goalkeeper')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='squad',
            field=models.IntegerField(choices=[(4, 'Freshman Red'), (1, 'Freshman'), (2, 'JV'), (3, 'Varsity')]),
        ),
    ]
