# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171208_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='klass',
            field=models.IntegerField(choices=[(1, b'Freshman'), (2, b'Sophomore'), (3, b'Junior'), (4, b'Senior')], verbose_name=b'Class'),
        ),
    ]
