# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post'),
        ('app', '0008_auto_20171208_1701'),
    ]

    operations = [
    ]
