# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171215_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.AddField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='squad',
            field=models.IntegerField(choices=[(4, 'Freshman Red'), (1, 'Freshman'), (2, 'JV'), (3, 'Varsity')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='klass',
            field=models.IntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')], verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posted'),
        ),
    ]
