# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_link_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
