# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_player_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgur_client_id', models.CharField(max_length=255)),
                ('imgur_client_secret', models.CharField(max_length=255)),
                ('imgur_access_token', models.CharField(max_length=255)),
                ('imgur_refresh_token', models.CharField(max_length=255)),
            ],
        ),
    ]
