# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='imgur_access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='imgur_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='imgur_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='imgur_refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
