# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_settings_imgur_token_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='imgur_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='imgur_account_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='imgur_token_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
