# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180116_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Most Individual Assists in a Game'), (2, 'Most Individual Goals in a Game'), (3, 'Most Saves in a Game'), (4, 'Most Individual Assists in a Season'), (5, 'Most Individual Goals in a Season'), (6, 'Most Saves in a Season'), (7, 'Most Individual Career Assists'), (8, 'Most Individual Career Goals'), (9, 'Most Career Saves'), (10, 'Longest Winning Streak'), (11, 'Most Wins in a Season'), (12, 'Most Shutouts'), (13, 'Best Playoff Appearance')])),
                ('record', models.CharField(max_length=32)),
                ('season', models.CharField(max_length=9)),
                ('player', models.CharField(blank=True, max_length=65)),
            ],
        ),
    ]
